#!/bin/bash
# chmod ug+x dev
clear

echo "Starting Dev"
ttab -t 'root-config' -d ./packages/root-config npm start
ttab -t 'appshell' -d ./packages/appshell npm start
echo "Navigate to http://localhost:9000"
echo ""