#!/bin/bash
# If you get permissions error, run this
# chmod ug+x check
clear

echo 'Lerna bootstraps, formats with prettify, lints & then tests'

# If runnng this is green, we can deploy

npx lerna bootstrap
npx lerna run format
npx lerna run lint:fix
npx lerna run test
