#!/bin/bash
# chmod ug+x functions
clear
echo "Starting firebase functions (API & SSR)"

ttab -t 'assets' npm run assets
ttab -t 'watch' -d ./packages/firebase npm run watch
ttab -t 'functions' -d ./packages/firebase npm run start

echo "http://localhost:5001/listingslab-app/us-central1/API"