#!/bin/bash
# chmod ug+x functions
clear
echo "Start and watch firebase functions (ASSETS & SSR)"

ttab -t 'watch' -d ./packages/firebase npm run watch
ttab -t 'functions' -d ./packages/firebase npm run start

echo "http://localhost:5001/listingslab-app/us-central1/SSR"