#!/bin/bash
# chmod ug+x ssr
clear
echo "Listingslab Single SPA with Server Side Rendering Started"
ttab -t 'functions' -d ./packages/firebase npm run serve
ttab -t 'watch' -d ./packages/firebase npm run watch
ttab -t 'public' npm run serve
ttab -t 'root-config' -d ./packages/root-config npm run start
ttab -t 'menu' -d ./packages/menu npm run start
ttab -t 'shared' -d ./packages/shared npm run start
ttab -t 'filebrowser' -d ./packages/filebrowser npm run start
ttab -t 'article' -d ./packages/article npm run start

echo "http://localhost:5001/listingslab-app/us-central1/SSR"