#!/bin/bash
# chmod ug+x ssr
clear

ttab -t 'functions' -d ./packages/firebase npm run serve
ttab -t 'watch' -d ./packages/firebase npm run watch
ttab -t 'public' npm run serve
ttab -t 'root-config' -d ./packages/main npm start
ttab -t 'menu' -d ./packages/menu npm start
ttab -t 'shared' -d ./packages/shared npm start
ttab -t 'filebrowser' -d ./packages/filebrowser npm start

clear
echo "Listingslab Single SPA with Server Side Rendering Started"
echo "http://localhost:5001/listingslab-app/us-central1/SSR"