#!/bin/bash
# If you get permissions error, run this
# chmod ug+x standalone
clear

echo 'Standalone Microfrontends; shared,' $1

ttab -t 'shared' -d ./packages/shared npm run start:standalone
ttab -t 'microfrontend' -d ./packages/$1 npm run start:standalone