#!/bin/bash
# chmod ug+x start
clear
echo "Server Side Rendering Started"


ttab -t 'root-config' -d ./packages/root-config npm run start
ttab -t 'persona' -d ./packages/persona npm run start
ttab -t 'shared' -d ./packages/shared npm run start
ttab -t 'viewer' -d ./packages/viewer npm run start

ttab -t 'watch' -d ./packages/firebase npm run watch
ttab -t 'functions' -d ./packages/firebase npm run serve

echo "http://localhost:5001/listingslab-app/us-central1/SSR"